### ISSUE TITLE
2020 Website

### ISSUE THREAD

**Issue by travismiller** [techlahoma/200ok-site#112]
Too early to discuss?

While thoughts are fresh working on the current version, it might be good to discuss current challenges and possible improvements.

Some initial thoughts to consider:
- What goals can be stated for the website?
- What existing and/or new features are important?
  - Map is currently disabled (#77)
  - Provide promotional social media assets for speakers, sponsors, and attendees ([Slack](https://techlahoma.slack.com/archives/C49ESL7JL/p1556247917011900))
- Automated deployments? ([Slack](https://techlahoma.slack.com/archives/C49ESL7JL/p1556244408009100))
  - [Travis CI + GitHub Pages](https://docs.travis-ci.com/user/deployment/pages/)
  - [Netlify](https://www.netlify.com/)
  - [Zeit Now](https://zeit.co/)
  - [GitHub Actions](https://github.com/features/actions)
- Review URLs?
  - [Netlify](https://www.netlify.com/docs/custom-domains/#branch-subdomains)
  - [Zeit Now](https://zeit.co/docs/v2/domains-and-aliases/aliasing-a-deployment/)
- Scheduled changes?
  - Call to action updates (e.g. early-bird open and close #110)
- 2019 is 4th iteration of current solution. Still happy with Hexo?
  - If not, what is important in selecting?
  - https://www.staticgen.com/
- ?

/cc @maxxcrawford @groovecoder

**Comment by maxxcrawford** [comment]
Is there any survey questions we can ask to this year's attendees to help drive some of this decision making? _(I know a large portion of the discussion points are not applicable)_

**Comment by travismiller** [comment]
Have we done a post conference survey before? Seems like a higher level thing that might include questions that pertain to the website.

**Comment by travismiller** [comment]
I'm closing the following issues on GitHub under the assumption that the site will have a significant overhaul this year.

- #43
- #65
- #77

/cc @maxxcrawford @groovecoder @kendallcorner @carlosangon @lesleyjanenorton
