### ISSUE TITLE
Replace node_module commands with npm run commands

### ISSUE THREAD

**Issue by maxxcrawford** [techlahoma/200ok-site#113]
Add scripts block to `package.json` to make command running easier. 

`./node_modules/.bin/hexo serve` becomes `npm run serve`, etc

https://docs.npmjs.com/cli/run-script

**Comment by travismiller** [comment]
@maxxcrawford these already exist.

```json
  "scripts": {
    "start": "hexo server",
    "build": "hexo generate",
    "deploy": "hexo deploy"
  },
```

**Comment by maxxcrawford** [comment]
🙈

**Comment by maxxcrawford** [comment]
🙈
