### ISSUE TITLE
Speaker Cards for Social Media

### ISSUE THREAD

**Issue by carlosangon** [techlahoma/200ok-site#115]
Here are the 5 cards for the speakers giving full talks.

<img width="801" alt="1_Mey@2x" src="https://user-images.githubusercontent.com/2627624/57022032-85f28800-6bf3-11e9-8180-d50db3f39176.png">

<img width="801" alt="2_Michele@2x" src="https://user-images.githubusercontent.com/2627624/57022041-8ab73c00-6bf3-11e9-9f13-1062a83e7dfd.png">

<img width="801" alt="3_Christine@2x" src="https://user-images.githubusercontent.com/2627624/57022049-8f7bf000-6bf3-11e9-9092-bc57a00ae3a3.png">

<img width="801" alt="4_Jenn@2x" src="https://user-images.githubusercontent.com/2627624/57022073-9e62a280-6bf3-11e9-9561-4ede60080a44.png">

<img width="801" alt="5_Erick@2x" src="https://user-images.githubusercontent.com/2627624/57022082-a589b080-6bf3-11e9-9f23-dc85685b2154.png">

@techlahoma/200-ok 

Let me know if there is anything else I can do.

**Comment by maxxcrawford** [comment]
Good by me!
