### ISSUE TITLE
expert ready local sponsor

### ISSUE THREAD

**Issue by carlosangon** [techlahoma/200ok-site#121]
![expert_ready_local_sponsor](https://user-images.githubusercontent.com/2627624/57878150-07930a00-77df-11e9-8f04-89b80441285c.png)

@groovecoder

**Comment by groovecoder** [comment]
Looks good. I missed if we had these for all the other sponsors too?

**Comment by carlosangon** [comment]
![spiked_mace@2x-100](https://user-images.githubusercontent.com/2627624/57896901-a6882800-7818-11e9-8d6d-2765452b62c8.jpg)

![dojo@2x-100](https://user-images.githubusercontent.com/2627624/57896905-aab44580-7818-11e9-9178-6e397fb147b6.jpg)

**Comment by carlosangon** [comment]
@groovecoder Here is the rest of the local sponsors. I was never made aware about this either, or maybe I missed the discussion.  Either way I can create them if needed Luke.

**Comment by groovecoder** [comment]
@carlosangon - if you can that would be great. We can post social media thank-you's to the sponsors during the event.
