### ISSUE TITLE
200OK Netlify Account

### ISSUE THREAD

**Issue by travismiller** [techlahoma/200ok-site#156]
The goal is to setup a dedicated Netlify account for hosting 200ok.us.

Currently 200ok.us is hosted on GitHub pages.

Moving to Netlify offers additional features including but not limited to:
- review apps (review link per PR)
- Redirects
- Server side functions

I’ve been using my own Netlify account to deploy a copy of 200ok site for review links.

Setting up a dedicated account protects us from tying hosting to a single individual.

A dedicated account requires registering with an email address.

My recommendation is that an address purposed for 200ok organizers and/or site developers is one of the following:

- 200ok@techlahoma.org (Google Workspace group; currently forwards to Emily, Maxx, and Travis)
- organizers@200ok.us (mailgun? unsure of status)
- netlify@200ok.us (mailgun? a potential new forward)

It should forward to at least two individuals responsible for the maintenance of the website.

**Comment by maxxcrawford** [comment]
We have Goolge Workplace for `@techlahoma.org` emails. We can make a new one or an alias – whatever you recommend. That works for us. We can also make it more specific to this task:  `200ok-netlify@`, `200ok-hosting`, `200ok-website@`, etc.

**Comment by travismiller** [comment]
This is resolved with:
- a dedicated 200ok Netlify account. (password in 1Password)
- a dedicated 200ok GitHub account. (password in 1Password)
- site established on Netlify and DNS updated to use Netlify DNS.
