### ISSUE TITLE
Restore an email alias for organizers

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/200ok-site#2]
Last year, we had an organizers@200ok.us email address as a central point of contact for attendees, speakers, or sponsors to reach us. We also included it in our CoC as the point of contact for harassment and CoC abuse.

@the-simian: who could create us a 200ok-organizers@techlahoma.org alias?

**Comment by the-simian** [comment]
@groovecoder Good question, last year @datachomp  handled a lot of that, but we probably should get that reassigned to someone

**Comment by datachomp** [comment]
There is the main techlahoma@gmail.com  account... and at the DNS host level - there is a  catch-all record that forwards to the gmail account.   for a 200ok-organizers forwarder, someone with DNS access would need to go in and add the forward.

**Comment by amandaharlin** [comment]
@groovecoder you should have an email confirmation incoming for techlahoma.org email forwarding. accept it and i'll be able to add 200ok-organizers@techlahoma.org email forwarding.

is there anyone else we should add to this filter (patrick, john, etc)?

**Comment by groovecoder** [comment]
I also made organizers@200ok.us mailbox so I could register @200okevent new Twitter handle. (Twitter wouldn't let me recover the @200okconf one. :cry:)

We can keep them in sync as far as email forwarding goes. Which one do people think is best? organizers@200ok.us or 200ok-organizers@techlahoma.org ?

**Comment by amandaharlin** [comment]
oh yours sounds nice. that's perfectly fine to use.

**Comment by groovecoder** [comment]
I'll keep it to organizers@200ok.us now that we have it.

**Comment by groovecoder** [comment]
Okay, I set up organizers@200ok.us to forward to everyone on @techlahoma/200-ok team.
