### ISSUE TITLE
Add Speakers!

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/200ok-site#222]
| Name | Twitter | Company | Talk Title |
| --- | --- | --- | --- |
| Adnan Rahic | `@adnanrahic` | Cube Dev | Making Data Warehouses fast. A developer's story. |
| Pereware Pere | | | Non-UI - A User-obsessed Design Approach |
| Laurie Voss | `@seldo` | Netlify | Web development best practices: what the data tells us |
| Kylie Humpert | | LegalShield | Project != Program != Product |
| ? | | | |
| ? | | | |

They will each have photos and more info, but thought I would put in a little bit of info now

**Comment by jsonthebson** [comment]
Here's an image so you know who's who
![Screenshot 2022-05-02 105618](https://user-images.githubusercontent.com/23440332/166266032-dd8fdd2f-2891-4dfe-8096-116852d2e28b.png)

Perewari Pere (Preferred name: Pere)
![Perewari_Pere_Trameter](https://user-images.githubusercontent.com/23440332/166266218-e503ef1d-ab38-4753-9b04-6976b523d055.JPG)
Pere is a Human Factors Designer and CEO at Trameter. He got his Bachelor's in Computer Science and co-founded his first startup after that. He left to pursue his Master's in design where he got his MSc. in Human-Computer Interaction at Bentley University. Pere understands the importance of UX across all walks of life and has used it to introduce better solutions at Trameter, one of which he will be sharing today
LinkedIn: https://www.linkedin.com/in/perewaripere/ (no twitter)
Non-UI - A User-obsessed Design Approach

Adnan Rahic
![adnan-min-2](https://user-images.githubusercontent.com/23440332/166266421-dfa003cc-8ff9-4f10-a4c2-9c65d1098848.jpg)
I'm Adnan, and I've been a JavaScript developer since before Webpack existed. I'm a DevOps advocate and have been teaching people to code for 5+ years.
https://twitter.com/adnanrahic
https://www.linkedin.com/in/adnanrahic/
Making Data Warehouses fast. A developer's story.
https://adnanrahic.com/

Laurie Voss
![internet square wide](https://user-images.githubusercontent.com/23440332/166266550-afadf8b5-0693-4edf-9338-d92ba5ada6bd.jpeg)
I have been a web developer for 26 years, and I believe passionately in making the web bigger, better and more accessible to everyone. Places I've done that include Yahoo, npm, and now Netlify.
@seldo
Web development best practices: what the data tells us
seldo.com

Kylie Humpert
![Kylie Humpert 57_6818](https://user-images.githubusercontent.com/23440332/166266691-9ad03378-7436-4f49-9ad3-0ec8f0d6d7be.jpg)
Kylie is a program manager focused on working with engineers to build out backend platforms to enable innovation for front end application teams. With former roles in project management, program management, product management and data analysis, her passion is making complex topics easy to understand. When she’s not trying to change the world through data, you can find her exploring the midwest with her family, volunteering with local tech organizations, or working on her fledgling coding skills.
Project != Program != Product


Note: waiting on two more speaker's info. Don't have exact talk times yet either

**Comment by travismiller** [comment]
@jsonthebson  sorry I deleted the comment and can’t restore it. I thought I was just deleting the image with email addresses in it. 🤦‍♂️

**Comment by jsonthebson** [comment]
Perewari Pere (Preferred name: Pere) Non-UI - A User-obsessed Design Approach

Adnan Rahic Making Data Warehouses fast. A developer's story.

Laurie Voss Web development best practices: what the data tells us

Kylie Humpert Project != Program != Product

Tanya Janca Purple is the new black: Modern Approaches to Application Security

Taylor Beseda Functional Web Apps - The revenge of dynamic web apps

Here's a link to all the bios and twitters and things. I thought it might be easier. https://airtable.com/shrJhoG3k9O3GMGnF

The only photo we are missing is Taylor. But I attached one here. 
![1597094338250](https://user-images.githubusercontent.com/23440332/167299775-49ecd5b8-4462-4a8e-84eb-20856fe1f9b4.jpg)

Schedule is still being finalized, but I believe it will be, as seen below. So just put this schedule in and say "subject to change"
![image](https://user-images.githubusercontent.com/23440332/167299851-f6662fab-2fae-46c5-b70f-0d8493a2844d.png)
