### ISSUE TITLE
survey link

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/200ok-site#281]
https://docs.google.com/forms/d/e/1FAIpQLSeQn1sCDfgYw3JsWRCOvaTPHPmHqas2_VSEmTVnoyz4BhNcWA/viewform?usp=sf_link

**Comment by kacollins** [comment]
Does this still need to be done? It looks like it's for 2023, and I'm assuming that there will be a new survey for 2024.

**Comment by jsonthebson** [comment]
Nope!
