### ISSUE TITLE
Add ticket sales link

### ISSUE THREAD

**Issue by kacollins** [techlahoma/200ok-site#295]
Places to update: 
- [ ] Hero section
- [ ] Ticket section

Link: https://ti.to/techlahoma/200ok-2024

**Comment by maxxcrawford** [comment]
Please also update the link text to "Get Tickets"

**Comment by jsonthebson** [comment]
@maxxcrawford would you rather have the widget?

Heres that if you want it: <html>
  <head>
    <script src="https://js.tito.io/v2/with/inline" async></script>
  </head>
  <body>
    <tito-widget
      event="techlahoma/200ok-2024"
    ></tito-widget>
  </body>
</html>

**Comment by maxxcrawford** [comment]
@jsonthebson Create call! I think we should use the widget. We need additional items: 

```
<html>
  <head>
    <script src="https://js.tito.io/v2/with/inline" async></script>
  </head>
  <body>
    <tito-widget
      event="techlahoma/200ok-2024"
    ></tito-widget>
  </body>
</html>
```

**Comment by maxxcrawford** [comment]
Update: I added the widget to a separate ticket: https://github.com/techlahoma/200ok-site/issues/309

**Comment by HLVN-1** [comment]
I added the widget for ticket sales and added the text found on the ticket sales page in place of the lorem ipsum text! Thank you for the widget script.

**Comment by kacollins** [comment]
Done in #306
