### ISSUE TITLE
Update sponsorship link

### ISSUE THREAD

**Issue by kacollins** [techlahoma/200ok-site#299]
Change the "sponsor us" link to this PDF: ([Download file from Google Drive](https://drive.google.com/file/d/1VvH9_xyWEPjStxWd766-1xA42lvvkSod/view))

- [ ] Add PDF to `/content/sponsorship` directory
- [ ] Update the `href` to link to the new PDF
- [ ] Update two links: Hero section, Sponsors section

**Comment by HLVN-1** [comment]
I'll do this one, too.

**Comment by kacollins** [comment]
Done in #314
