### ISSUE TITLE
Add new Sponsor Rogue Recruitment

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/200ok-site#307]
Rogue Recruitment, H3 level sponsor. 
![rogue-recruitment-straight-line-red](https://github.com/techlahoma/200ok-site/assets/23440332/92fc5663-2081-4de7-bebc-e28888ac517d)
link to roguerectuitment.com

**Comment by kacollins** [comment]
@JakeFellwock Are you doing this?
