### ISSUE TITLE
Afterparty on schedule

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/200ok-site#327]
You can go ahead and update the schedule to show the afterparty is at Welltown Brewing, with a link to the address there if you'd like. "First drink is on us!"

**Comment by maxxcrawford** [comment]
Preview: 

<img width="439" alt="image" src="https://github.com/techlahoma/200ok-site/assets/2692333/f33be2bc-ea9c-45a8-be4d-8be1938f5d00">

Should we add some sort of 21+ ?
