### ISSUE TITLE
remove some text

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/200ok-site#330]
200OK is a web developer-focused conference run by Oklahoma’s nonprofit tech organization, Techlahoma. Our audience is interested in the newest web technologies and tools. Connect with fellow web professionals and some of the best speakers in the country for a day of presentations about leading web tech topics ~~plus join in hacking spaces, break-outs, and group discussions~~

later in the page, remove ~~Additional speaker biographies coming soon.~~

**Comment by HLVN-1** [comment]
I removed the text that was requested!
