### ISSUE TITLE
Abstract maxlength is different than validation

### ISSUE THREAD

**Issue by Bekt** [techlahoma/200ok-site#43]
On the talk proposal page, the "Abstract" textarea has a maxlength of 1000 characters, but the validation is set for 600.

Could we make the two the same? I would prefer 1000 because 600 characters is only 4-8 sentences. (600 characters / 6 average word len / 15 average sentence len).

**Comment by FlaminSeraphim** [comment]
@groovecoder @gregtatum is this a 200ok.us site issue or is this a different site that was used to collect all the proposals?
