### ISSUE TITLE
2018 speaker images

### ISSUE THREAD

**Issue by jsatt** [techlahoma/200ok-site#62]
![bonnie_milian](https://user-images.githubusercontent.com/498431/37067790-2798e90c-2171-11e8-9679-57bae76b15a8.jpg)
![carmen_bourlon](https://user-images.githubusercontent.com/498431/37067801-3e22f1b8-2171-11e8-9d6f-c5d24ed66549.jpg)
![cosmo_wolfe](https://user-images.githubusercontent.com/498431/37067806-403914e6-2171-11e8-8639-a78d605c59a0.png)
![darren_gibson](https://user-images.githubusercontent.com/498431/37067807-418bdc3e-2171-11e8-9dc7-363f651f39ac.jpeg)
![jennifer_wadella](https://user-images.githubusercontent.com/498431/37067813-48503cc2-2171-11e8-85ed-999aa865d584.jpg)
![lee_brant](https://user-images.githubusercontent.com/498431/37067814-4943b14a-2171-11e8-9a71-b289aec4827d.jpg)
![nir_kaufman](https://user-images.githubusercontent.com/498431/37067815-4a43da34-2171-11e8-918e-4889d5cad98b.png)

**Comment by carlosangon** [comment]
Old issue, should be deleted.

**Comment by maxxcrawford** [comment]
2018 speakers. Closing!
