### ISSUE TITLE
Round navigation buttons to match 2019 theme

### ISSUE THREAD

**Issue by maxxcrawford** [techlahoma/200ok-site#72]
Navigation buttons should match the prominent button design shape. (Color is fine!) 

## Screenshots

Current state: 

![image](https://user-images.githubusercontent.com/2692333/53032853-5249f380-3435-11e9-9958-af2727f66172.png)

Rounded corner example: 
![image](https://user-images.githubusercontent.com/2692333/53032902-6e4d9500-3435-11e9-9a83-8b03970ba29e.png)

**Comment by carlosangon** [comment]
Done

**Comment by maxxcrawford** [comment]
#78 resolved this.
