### ISSUE TITLE
Resize H1 for small mobile screens

### ISSUE THREAD

**Issue by maxxcrawford** [techlahoma/200ok-site#74]
Main `h1` doesn't fit the screen width on sub `350px` screens. Recommend a smaller font size up to 400px, and then return to current sizing. 

## Screenshot

![image](https://user-images.githubusercontent.com/2692333/53033433-a30e1c00-3436-11e9-8fcc-99c4d15a2c48.png)

**Comment by carlosangon** [comment]
Hmm, I can only think of iPhone 5 with a device width of 320.

http://screensiz.es/iphone-5-5c-5s

I'm not sure this is too critical in my opinion.

**Comment by maxxcrawford** [comment]
Will be resolved on https://github.com/techlahoma/200ok-site/pull/87
