### ISSUE TITLE
Update site DNS

### ISSUE THREAD

**Issue by maxxcrawford** [techlahoma/200ok-site#75]
From the [project settings](https://github.com/techlahoma/200ok-site/settings):

![image](https://user-images.githubusercontent.com/2692333/53033990-ef0d9080-3437-11e9-86f5-8b5dbda834c6.png)

https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by kendallcorner** [comment]
Should be fixed, let's check it in 24 hours or less

**Comment by kendallcorner** [comment]
Looks like it's all  good.
