### ISSUE TITLE
Update social icon hover color

### ISSUE THREAD

**Issue by maxxcrawford** [techlahoma/200ok-site#76]
Current hover color of social icon links (located in hero section) is low contrast. Recommend using the orange or green color. 

`#E34C39`
`#29C748`

## Screenshots

Hero: 
![image](https://user-images.githubusercontent.com/2692333/53034662-4bbd7b00-3439-11e9-87b3-3e56ba823207.png)

Detail: 
![image](https://user-images.githubusercontent.com/2692333/53034638-3e07f580-3439-11e9-8cc3-ab2ac137a67c.png)

**Comment by carlosangon** [comment]
I got this.

**Comment by maxxcrawford** [comment]
#78 resolved this.
