### ISSUE TITLE
Replace Google Maps embedded map with free alternative

### ISSUE THREAD

**Issue by maxxcrawford** [techlahoma/200ok-site#77]
Google Maps API update from last year requires a new setup, including a card on file to charge API usagse. Recommend to move to an alternative map service. 

https://www.openstreetmap.org 

Error message: 
> You have exceeded your request quota for this API. https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors

## Screenshot 

![image](https://user-images.githubusercontent.com/2692333/53034908-e3bb6480-3439-11e9-934c-81b41c322a0d.png)

**Comment by carlosangon** [comment]
Taking care of this now. Removing map temporarily.

**Comment by maxxcrawford** [comment]
@carlosangon Revised this issue and will leave as unresolved for now.

**Comment by carlosangon** [comment]
@maxxcrawford Copy that boss.

**Comment by travismiller** [comment]
Here.com has been recommended to me before. I’ve done zero research on it yet though.

**Comment by brianmcoates** [comment]
Mapbox with the usage that we would have on the site should be comfortably free
