### ISSUE TITLE
Add speaker schedule 

### ISSUE THREAD

**Issue by maxxcrawford** [techlahoma/200ok-site#84]

**Comment by groovecoder** [comment]
Last confirmed speaker is:

## WTF are Serverless Apps?


Serverless applications are changing the way that developers think about software development, release management, and infrastructure. Many myths and histories had been created around this concept and turn minds confused when choices are required to create new products in an existent environment. Attendees will learn about Serverless architecture concepts compared than traditional Microservices. By the use of real scenarios, they could understand the differences and challenges that we face in production environments and how to solve most of them as soon as possible.

We will explore the following topics:
- Which are Serverless applications?
- Best practices working in production environments
- Avoiding common problems such: Long-running processing, latency and complex application management (versioning, releases, tests)
- Which cases you should use Serverless applications based.

### Erick Wendel
Erick Wendel is a Speaker, Software Consultant and community Co-organizer in Brazil. Named by Microsoft as Most Valuable Professional, and by Google as Google Developer Expert, a specialist in Node.js and Javascript Applications. He is a Software Independent Architect who helps companies to make better and cheaper applications using Serverless architectures, Container based applications, and Hybrid Cloud solutions.
