### ISSUE TITLE
hex deploy didn't update site?

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/200ok-site#9]
Hmm ... I tried following the hex deploy instructions from the README, but this time it didn't update the site with what's on the master branch? Do I have to make my changes on the gh-pages branch?

**Comment by TatumCreative** [comment]
Shouldn't have to... you might now have re-generated the local files or need to regenerate it.

```
hexo clean
hexo generate
hexo deploy
```

**Comment by the-simian** [comment]
hey, also gh-pages can cache aggressively. try waiting a few mins, and check again if you are pretty sure you did it right

**Comment by groovecoder** [comment]
Hmm ... `clean`, `generate`, and `deploy` did the trick. I probably forgot to `generate` last time.
